name: "Step 2: Naive GitOps"

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1 
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.PAT }} # `PAT` is a secret that contains your Personal Access Token with `write:packages` scope

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          ghcr.io/${{ github.repository }}:${{ github.sha }}

    - name: Fetch Gimlet CLI
      run: |
        # curl -L https://github.com/gimlet-io/gimlet-cli/releases/download/v0.3.0/gimlet-$(uname)-$(uname -m) -o gimlet
        curl -L https://github.com/gimlet-io/gimlet-cli/releases/download/tip/gimlet-$(uname)-$(uname -m) -o gimlet
        chmod +x gimlet

    - name: Checkout GitOps repo
      uses: actions/checkout@v2
      with:
        repository: gimlet-io/fosdem-2021-gitops
        token: ${{ secrets.PAT }} # `PAT` is a secret that contains your Personal Access Token with `repo` scope
        path: gitops

    - name: Write to GitOps repository
      run: |
        cat manifests/deployment.yaml | envsubst | \
          ./gimlet gitops write -f - \
            --env staging \
            --app fosdem-2021 \
            --gitops-repo-path gitops \
            -m "Releasing $GITHUB_SHA"
        (cd gitops/; git push origin main)
