name: "Step 1: kubectl apply -f"

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1 
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT }} # `PAT` is a secret that contains your Personal Access Token with `write:packages` scope

      - name: Start Kubernetes cluster
        uses: engineerd/setup-kind@v0.5.0

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.sha }}

      - name: Kubernetes deploy
        run: |
          kubectl cluster-info
          kubectl get pods -n kube-system
          cat manifests/deployment.yaml | envsubst | kubectl apply -f -
          cat manifests/service.yaml | kubectl apply -f -
